---
resource_types:
  - name: git-branches
    type: registry-image
    source:
      repository: aoldershaw/git-branches-resource

resources:
  - name: every-3-hours
    type: time
    icon: clock-outline
    source:
      interval: 3h

  - name: branches
    type: git-branches
    icon: github
    source:
      git_config:
        - name: safe.directory
          value: '*'
      password: ((github-token))
      skip_ssl_verification: true
      uri: git@github.com:dashaun-demo/spring-petclinic.git
      username: ((git-username))

  - name: upgrade-petclinic-demo
    type: git
    icon: pipe
    source:
      git_config:
        - name: safe.directory
          value: '*'
      password: (( git-password ))
      skip_ssl_verification: true
      uri: https://github.com/dashaun-tanzu/upgrade-petclinic-demo.git
      username: (( git-username ))

  - name: repo
    type: git
    icon: github
    source:
      branch: main
      git_config:
        - name: safe.directory
          value: '*'
      password: ((github-token))
      skip_ssl_verification: true
      uri: git@github.com:dashaun-demo/spring-petclinic.git
      username: ((git-username))

jobs:
  - name: set-feature-pipelines
    plan:
      - in_parallel:
          - get: branches
            trigger: true
          - get: upgrade-petclinic-demo
      - load_var: branches
        file: branches/branches.json
      - across:
          - var: branch
            values: ((.:branches))
        set_pipeline: ((.:branch.name))
        file: upgrade-petclinic-demo/pipelines/branch.yml
        vars: { branch: ((.:branch.name)),
                github-token: ((github-token)),
                dockerhub-user: ((dockerhub-user)),
                dockerhub-token: ((dockerhub-token)),
                git-username: ((git-username)) }
  - name: spring-application-advisor
    serial: true
    public: true
    plan:
      - get: every-3-hours
        trigger: true
      - get: repo
        trigger: true
      - task: spring-application-advisor
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: dashaun/task-runner
              username: ((dockerhub-user))
              password: ((dockerhub-token))
              tag: 1.0.4-linux-x86
          inputs:
            - name: repo
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                set +x
                export GIT_TOKEN_FOR_PRS=((github-token))
                export ADVISOR_SERVER=https://saa-remix.dashaun.live
                source "/root/.sdkman/bin/sdkman-init.sh"
                cd repo
                sdk install java 21.0.2-graalce
                sdk use java 21.0.2-graalce
                set -x
                advisor -version
                advisor build-config get
                advisor upgrade-plan get
                advisor upgrade-plan apply --push